9.0/Dockerfile
To avoid ImportError: cannot import name IncompleteRead
=> Upgrade pip

9.0/Dockerfile, 9.0/bin/docker-entrypoint.sh, 9.0/bin/migrate, 9.0/etc/openerp.cfg.tmpl, README.md, example/README.md, example/docker-compose.yml, example/odoo/Dockerfile
* The ADDONS_PATH must be set in the Dockerfile of the projects
* Add a 'DEMO' environment variable
Allowing to disable demo data, enable only for Scenario, only for Odoo's
demo data or enable both.
=> Add a common configuration file and a demo flag

example/docker-compose.yml
Refer to
https://github.com/camptocamp/docker-odoo-nginx
=> Change nginx container to camptocamp's public image

9.0/base_requirements.txt, HISTORY.rst
Details:
* https://github.com/camptocamp/marabunta/releases/tag/0.4.0
* https://github.com/camptocamp/anthem/releases/tag/0.3.0
=> Upgrade marabunta and anthem libraries

bin/runtests
Was leading to error when travis was launching tests.
Tested on V10 by @cyrilgdn @yvaucher
=> remove unsuseful pathdir to odoo as it on his PATH

10.0/Dockerfile, 10.0/etc/odoo.cfg.tmpl, 9.0/Dockerfile, 9.0/etc/openerp.cfg.tmpl, HISTORY.rst, README.md, bin/docker-entrypoint.sh, bin/migrate, bin/runtests, bin/testdb-gen, bin/testdb-update, bin/wait_postgres.sh, example/odoo/migration.yml
Default is still db, but it can be changed to avoid to add an external
link.
Alternative of https://github.com/camptocamp/docker-odoo-project/pull/17
=> Possibility to customize the db hostname

10.0/etc/odoo.cfg.tmpl, 9.0/etc/openerp.cfg.tmpl
=> Add server_wide_modules in odoo.cfg

10.0/base_requirements.txt, 9.0/base_requirements.txt
https://github.com/odoo/odoo/issues/17914
=> Upgrade psycopg2 to 2.7.1

10.0/base_requirements.txt, 9.0/base_requirements.txt, HISTORY.rst
By upgrading anthem to 0.10.0 and marabunta to 0.7.0.
=> Enable publishing of maintenance web page

10.0/base_requirements.txt, 11.0/Dockerfile, 11.0/base_requirements.txt, 9.0/base_requirements.txt, README.md
Companion PR https://github.com/camptocamp/anthem/pull/36
=> Add `ODOO_DATA_PATH` env var

10.0/base_requirements.txt, 9.0/base_requirements.txt, HISTORY.rst
=> Upgrade six to 1.10.0

10.0/Dockerfile, 11.0/Dockerfile, 9.0/Dockerfile, HISTORY.rst, install/setup-pip.sh
=> Disable pip's cache dir to reduce size of images

10.0/extra_requirements.txt, 11.0/extra_requirements.txt, 9.0/extra_requirements.txt, HISTORY.rst
https://jira.camptocamp.com/browse/BS-287
=> [ADD] Update `cryptography` dependency to a newer version

10.0/Dockerfile, 11.0/Dockerfile, 9.0/Dockerfile, build.sh, common/.coveragerc
Filter `__manifest__.py` files and content of `tests` folder
=> Add coveragerc in working dir

10.0/extra_requirements.txt, 11.0/extra_requirements.txt, 12.0/extra_requirements.txt, 9.0/extra_requirements.txt
=> Bump paramiko version

bin/docker-entrypoint.sh
To fix the problem with this parts on Dockerfile from odoo-template Line 33 and 34
=> Fix BEFORE_MIGRATE_ENTRYPOINT_DIR & START_ENTRYPOINT_DIR to remove /odoo

HISTORY.rst
=> Add missing item in history 

10.0/base_requirements.txt, 11.0/base_requirements.txt, 12.0/base_requirements.txt, 9.0/base_requirements.txt
=> Bump requests version

10.0/base_requirements.txt, 11.0/base_requirements.txt, 12.0/base_requirements.txt, 9.0/base_requirements.txt, HISTORY.rst, README.md
- fixing CVE-2017-18342
- small change on odoo-template https://github.com/camptocamp/odoo-template/pull/315
=> BSRD-169: CVE-2017-18342

11.0/extra_requirements.txt, 12.0/extra_requirements.txt, 9.0/extra_requirements.txt, HISTORY.rst
Was introduced in https://github.com/camptocamp/docker-odoo-project/commit/6ccb0a9a8ed835ef28ed91b3ef13b6f8f0814ea2
=> Remove duplicate magento in extra_requirements

10.0/base_requirements.txt, 11.0/base_requirements.txt, 12.0/base_requirements.txt, 9.0/base_requirements.txt, HISTORY.rst
=> Pin pyyaml to latest 4.x

10.0/base_requirements.txt, 11.0/base_requirements.txt, 12.0/base_requirements.txt, 9.0/base_requirements.txt, HISTORY.rst, install/package_odoo_9.0_10.0.sh
Bump Jinja version
and fix issue with libc-ares2
=> Bump Jinja version to 2.10.1

10.0/base_requirements.txt, 11.0/base_requirements.txt, 12.0/base_requirements.txt, 9.0/base_requirements.txt
=> Bump urllib3 version to 1.24.2

10.0/templates/odoo.cfg.tmpl, 11.0/templates/odoo.cfg.tmpl, 12.0/templates/odoo.cfg.tmpl, 7.0/templates/openerp.cfg.tmpl, 8.0/templates/openerp.cfg.tmpl, 9.0/templates/openerp.cfg.tmpl, HISTORY.rst, README.md
Add the ability to have additional parameters in `odoo.cfg` file
=> Add ADDITIONAL_ODOO_RC environment variable

10.0/base_requirements.txt, 11.0/base_requirements.txt, 12.0/base_requirements.txt, 13.0/base_requirements.txt, 7.0/base_requirements.txt, 8.0/base_requirements.txt, 9.0/base_requirements.txt, HISTORY.rst
Bump version to 5.7.0 to fix security issue CVE-2019-18874
Tested with Odoo v7 through v13
=> Bump psutil to fix security issue

13.0/base_requirements.txt, HISTORY.rst
=> Bump various libraries in v13 to match Odoo's requirements

HISTORY.rst, install/setup-pip.sh
Attempt to superseed https://github.com/camptocamp/docker-odoo-project/pull/130
=> disable pip version checks

14.0/base_requirements.txt
need to be able to import XLSX files into Odoo 14.0
=> add xlrd >= 1.0.0 as dependency

10.0/base_requirements.txt, 11.0/base_requirements.txt, 12.0/base_requirements.txt, 13.0/base_requirements.txt, 14.0/base_requirements.txt, 7.0/base_requirements.txt, 8.0/base_requirements.txt, 9.0/base_requirements.txt, HISTORY.rst
Changelog of this new release: https://github.com/camptocamp/marabunta/releases/tag/0.10.5
=> Update Marabunta to 0.10.5

13.0/base_requirements.txt, 14.0/base_requirements.txt, 15.0/Dockerfile, 15.0/base_requirements.txt, HISTORY.rst
Same versions of dependencies between 14.0 and 15.0 to ease future maintenance.
=> [15.0] Align versions with 14.0

bin/docker-entrypoint.sh
=> fix: Fix args unpacking in docker-entrypoint.sh

11.0/Dockerfile, 12.0/Dockerfile, 13.0/Dockerfile, 14.0/Dockerfile, 15.0/Dockerfile, 16.0/Dockerfile
group successive RUN commands in a single one.
remove duplicate RUN /install/dockerize.sh
=> [IMP] reduce number of layers

16.0/Dockerfile
=> feat: switch 16.0 to python 3.10
