9.0/bin/docker-entrypoint.sh
HISTORY.rst

The build runs `pip install -e` on the odoo src, which creates an
odoo.egg-info directory *inside /opt/odoo/src*. So when we run a
container with a volume shared with the host, we don't have this
.egg-info (at least the first time).
Correction: When it happens, we reinstall the odoo package. We don't want to run it anytime
because it would slow the start of the containers

Fix error pkg_resources.DistributionNotFound: odoo==9.0c

---

10.0/Dockerfile
10.0/base_requirements.txt
9.0/Dockerfile
9.0/base_requirements.txt
HISTORY.rst
README.md
bin/docker-entrypoint.sh
bin/testdb-gen
bin/testdb-update
example/docker-compose.override.yml
example/odoo/Dockerfile

pytest is included and can be invoked when starting a container. It needs an existing database to run the tests:
```
docker-compose run --rm -e DB_NAME=dbtest -e MIGRATE=False -e DEMO=True odoo odoo --workers=0 --log-level=warn --stop-after-init -i my_addon
docker-compose run --rm -e DB_NAME=dbtest odoo pytest -s odoo/local-src/my_addon/tests/test_feature.py::TestFeature::test_it_passes
```
**Warning**
Compatibility break:
the Workdir of the container will be ``/opt`` instead of ``/opt/odoo``.
The reason is that it allows a more natural transition between the project from
the outside of the container and from the inside. Meaning, if we run the following command:
docker-compose run --rm -e DB_NAME=dbtest odoo pytest -s odoo/local-src/my_addon/tests/test_feature.py::TestFeature::test_it_pass …

Add pytest

---

10.0/Dockerfile
9.0/Dockerfile
HISTORY.rst
Makefile
README.md
bin/docker-entrypoint.sh
start-entrypoint.d/000_set_base_url

Any script in any language placed in `/opt/odoo/start-entrypoint.d` will be
executed just between the migration and the start of Odoo. The order of
execution of the files is determined by the `run-parts` 's rules.
The database is guaranteed to exist at this point so you can run queries on it.
The scripts are run only if the command is `odoo`/`odoo.py`.
You can add your own scripts in this directory. They must be named something
like `010_abc` (`^[a-zA-Z0-9_-]+$`) and must have no extension (or it would not
be picked up by `run-parts`).

Add custom scripts in /opt/odoo/start-entrypoint.d

---

10.0/base_requirements.txt
9.0/base_requirements.txt

It's an optional lib but a must-have as emails will be sent with a
text version.

Add html2text lib

---

10.0/base_requirements.txt
9.0/base_requirements.txt

See https://github.com/OCA/maintainer-quality-tools/commit/5b4b67e757611ac393aaf4434195ca5aa0cd4502

[fix] Remove deprecated download.gna.org for PyChart

---

10.0/base_requirements.txt
9.0/base_requirements.txt
HISTORY.rst

It is a requirement from odoo. For now we are unable to build an image.

Add ofxparse as requirement as seen in odoo

---

10.0/base_requirements.txt

Add odoo-autodiscover to base_requirements to enable working with Odoo addons packaged as python wheels. (Version 10.0)
Solves https://github.com/camptocamp/docker-odoo-project/issues/38

Add odoo-autodiscover  to base_requirements 

---

10.0/Dockerfile
10.0/base_requirements.txt
9.0/Dockerfile
9.0/base_requirements.txt
HISTORY.rst

To prevent unnecessary upgrades of libraries. See https://github.com/pypa/pip/pull/3972

Use pip development version

---

11.0/Dockerfile
HISTORY.rst

* python-libxslt1 pulls Python 2.7 which takes space. It is unlikely that
we need it as we use Python 3. We need to install libxslt1.1 though
* The wkhtmltopdf archive contains a .so in the lib directory with
several symlinks pointing to the same file. By default cp will copy
several times the same file:
-rwxr-xr-x 1 root staff 45134232 Jan 11 14:23 libwkhtmltox.so
-rwxr-xr-x 1 root staff 45134232 Jan 11 14:23 libwkhtmltox.so.0
-rwxr-xr-x 1 root staff 45134232 Jan 11 14:23 libwkhtmltox.so.0.12
-rwxr-xr-x 1 root staff 45134232 Jan 11 14:23 libwkhtmltox.so.0.12.4
Instead of:
root@c384d2ebae3c:/usr/local/lib# ls -l
total 43984
lrwxrwxrwx 1 root root        22 Feb 27  2015 libwkhtmltox.so -> libwkhtmltox.so.0.12.1
lrwxrwxrwx 1 root root        22 Feb 27  2015 libwkhtmltox.so.0 -> …

Reduce size of the 11.0 image

---

HISTORY.rst
start-entrypoint.d/001_set_report_url

This script sets the report.url property to guide wktmltopdf to the correct location. If nothing is given the web.base.url is used. Thats why there is no default value.

Add script to set report.url

---

11.0/base_requirements.txt

this is now a core requirement, well not really mandatory but is nice to have anyway.
Upstream PR https://github.com/odoo/odoo/pull/22482

Add `phonenumbers` requirement

---

10.0/Dockerfile
11.0/Dockerfile
9.0/Dockerfile
HISTORY.rst
Makefile
install/dockerize.sh
install/gosu.sh

If the http_proxy environment variable is set, it will be used for
reaching the gpg key server. When the variable is empty, the behavior is
the same than before (no proxy).

Allow usage of a proxy for the gpg keyservers

---

10.0/Dockerfile
11.0/Dockerfile
9.0/Dockerfile
HISTORY.rst

The installed version of setuptools fail with:
```
Traceback (most recent call last):
File "/usr/local/bin/odoo.py", line 4, in <module>
__import__('pkg_resources').require('odoo==9.0c')
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
working_set = WorkingSet._build_master()
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
ws.require(__requires__)
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 645, in resolve
requirements.extend(dist.requires(req.extras)[::-1])
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2401, in requires
dm = self._dep_map
File …
```

Upgrade setuptools

---

bin/runtests

By consistency, in the commit 0c58332 I changed the path to the odoo-bin
script in both places it was used.
However, as long as 'coverage run' accepts a file which doesn't to be
executable, the first call is executed. We could call python2 or python3
on ${ODOO_BIN_PATH}, but the "odoo" script is there for that. So let's
keep "odoo" for the install and use the "odoo-bin" only for 'coverage
run' where it's required.
For the record, the 'odoo-bin' script is eXecutable in the git
repository, but in some cases we optimize the build of the image by
downloading a tar, and it seems the x flag is absent there.

Fix permission issue when installing runtests db

---

10.0/Dockerfile
11.0/Dockerfile
9.0/Dockerfile

Bypass the wrapper to call pip with `python -m pip` 
This is an attempt to fix travis error:
```
+ pip3 install -U pip setuptools
Collecting pip
Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
Collecting setuptools
Downloading https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl (567kB)
Installing collected packages: pip, setuptools
Found existing installation: pip 9.0.1
Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Found existing installation: setuptools 33.1.1
Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr …
```

Fix travis pip install

---

10.0/Dockerfile
11.0/Dockerfile
9.0/Dockerfile

By default report.url fallbacks to web.base.url.
As the reports are very workers consuming (needs 3 workers),
we thought that it would be better if they hit the public url
to round robin on the hosts if you have more than one.
This is true but many times does not work because of networks issues,
caching issues, etc (like on minions for instance).
With this change we force it always to be `localhost:8069`.

Always set env var `ODOO_REPORT_URL`

---

Makefile
README.md
bin/runmigration
bin/runtests

It should no longer be in /opt, following the restructuration.

Fix path of .cachedb

---

bin/runtests

Launch of tests is already included in coverage run line.
Currently tests are run twice.

Launch tests only once

---

test.sh

This reverts commit 484f005480f4d66d36a8856db2c6a2b9ccff3f2f.
This commit was added because Odoo did not have a 12.0 branch yet.
Now that it is there, it must be reverted otherwise the 12.0 image is tested against master.

Revert "Temporary fix test waiting Odoo release 12.0"

---

11.0/Dockerfile
12.0/Dockerfile
9.0/Dockerfile
HISTORY.rst

Must be done only in batteries flavor (see Dockerfile-batteries):
https://github.com/camptocamp/docker-odoo-project/blob/master/common/Dockerfile-batteries#L4

Remove bad copy of extra_requirements in Dockerfile

---

12.0/Dockerfile
HISTORY.rst
install/wkhtml_12_5.sh

Above the result with 0.12.4
Probably broken with last odoo commits.
Below with 0.12.5.1

Add script to install wkhtml 0.12.5.1

---

10.0/base_requirements.txt
11.0/base_requirements.txt
12.0/base_requirements.txt
13.0/base_requirements.txt
7.0/base_requirements.txt
8.0/base_requirements.txt
9.0/base_requirements.txt
HISTORY.rst

* Bump `werkzeug` to 0.16.0
* Bump several libraries (v7+8 only)

Bump libraries to fix security alerts

---

7.0/base_requirements.txt

To avoid this error in 7.0
```
2019-11-05 10:25:48,202 313 ERROR ? openerp.service.workers: Worker (313) Exception occured, exiting...
Traceback (most recent call last):
File "/odoo/src/openerp/service/workers.py", line 302, in run
self.start()
File "/odoo/src/openerp/service/workers.py", line 344, in start
self.server = WorkerBaseWSGIServer(self.multi.app)
File "/odoo/src/openerp/service/workers.py", line 350, in __init__
werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 705, in __init__
self.port = self.socket.getsockname()[1]
File "/usr/lib/python2.7/socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
File "/usr/lib/python2.7/socket.py", line 170, in _dummy
raise error(EBADF, 'Bad file …
```

[7.0] Werkzeug version 0.16.0 -> 0.9.6 to avoid Bad file descriptor Error

---

8.0/base_requirements.txt
HISTORY.rst

Downgrade Pillow for Odoo V8 to avoid errors like : 
`ParseError: "cannot write mode RGBA as JPEG"`

Fix Pillow issue in v8

---

8.0/base_requirements.txt
HISTORY.rst

Downgrade `werkzeug` version to avoid errors like
`error: [Errno 9] Bad file descriptor`

Fix Werkzeug issue in V8

---

11.0/Dockerfile

It is not done in Versions 12 & 13.
Tested locally with:
```
make VERSION=11.0
make VERSION=11.0 test
```

Fix coverage wrongly moved

---

10.0/Dockerfile
7.0/Dockerfile
7.0/base_requirements.txt
8.0/Dockerfile
8.0/base_requirements.txt
9.0/Dockerfile
9.0/base_requirements.txt
HISTORY.rst
install/wkhtml_12_5.sh
install/wkhtml_12_5_1.sh

* Pin setuptools and dependencies to ensure Python 2 support in Odoo<=10
* Fix deprecated download links for wkhtmltopdf
Fixes #128

Build fixes (python libraries + wkhtmltopdf)

---

10.0/base_requirements.txt
11.0/base_requirements.txt
12.0/base_requirements.txt
13.0/base_requirements.txt
9.0/base_requirements.txt
HISTORY.rst

Bump `Pillow` to version 6.2.2 to fix CVE-2019-19911 and CVE-2020-5313
Requirements for Odoo v7-8 cannot be updated as they are too old to handle new version of `Pillow` library

Bump Pillow to fix security issue

---

HISTORY.rst
common/Dockerfile-batteries
common/Dockerfile-onbuild

Not sure if we should remove the lines (or update them) for v < 11

Fix missing .coveragerc for v11-12-13

---

10.0/base_requirements.txt
7.0/base_requirements.txt
8.0/base_requirements.txt
9.0/base_requirements.txt
HISTORY.rst

This is the last supported version for Python 2.7
This applis for Odoo <= 10.0
Fixes #141

Fix pytest to 4.6

---

bin/docker-entrypoint.sh

When using docker-compose exec the entrypoint is not executed and so
the export of psql variable is not done.
This change will modify the bashrc configuration so if you do a
docker-compose exec odoo gosu odoo bash
you will have the right psql variable
@guewen @hpar
The alternative solution will be to use psql vars into environment file instead of custom one; but this is a broken change

Fix missing variable with docker-compose exec

---

HISTORY.rst
README.md
bin/docker-entrypoint.sh

This might already have happened to you. You just want to launch a shell to check something in a database or launch the `--help` to check odoo parameters. Before this PR you would likely have to add explicitly a `-e MIGRATE=False`
The 2 following commands do not trigger entrypoints anymore
and are be executed straight forward.
docker-compose run --rm odoo odoo shell [...]
docker-compose run --rm odoo odoo [...] --help [...]

shell and --help bypass entrypoints

---

install/wkhtml_12_1_2.sh

This PR is intended to circumvent the deletion of the package for wkhtmltopdf version 0.12.1.2 on Odoo side as it was considered deprecated.
I manually recompiled the package, but the solution to integrate it in the image proposed here is far from being optimal, so I gladly update it if you have any better idea

Fix wkhtmltopdf version for Odoo version <= 10

---

bin/runtests

When in test environments, `dbfilter` still refers to `odoodb` in `/etc/odoo.cfg`.
Problem appears in HttpCase when trying to authenticate, dbfilter denies the connection.
```bash
2020-07-20 00:00:00,000 102 WARNING ? odoo.http: Logged into database 'odoodb_test', but dbfilter rejects it; logging session out.
```

Fix dbfilter in test environment

---

14.0/base_requirements.txt
HISTORY.rst

Odoo's version is stuck to requsets == 2.21.0
This forces us to downgrade to a compatible version of `urllib3`

[14.0] Downgrade urllib3 to match requests requirement

---

11.0/base_requirements.txt
12.0-buster/base_requirements.txt
12.0/base_requirements.txt
13.0/base_requirements.txt
14.0/base_requirements.txt
HISTORY.rst

According to https://github.com/acsone/odoo-autodiscover#odoo-autodiscover
Thus we should be able to safely remove it and restore the CI

odoo-autodiscover is not necessary for Odoo 11.0 and later

---

10.0/Dockerfile
11.0/base_requirements.txt
12.0/base_requirements.txt
7.0/Dockerfile
8.0/Dockerfile
9.0/Dockerfile
HISTORY.rst
build.sh
install/wkhtml_12_1_2.sh

All version after watchdog 1.0.0 dropped support for Py3.5

[11.0,12.0] Pin watchdog before Py3.5 compat break

---

10.0/Dockerfile
7.0/Dockerfile
8.0/Dockerfile
9.0/Dockerfile
build.sh
install/wkhtml_12_1_2.sh

Following #147 
This avoid putting an extra 14MB in images > 10.0

Copy 14MB of deb only on older versions

---

10.0/Dockerfile
10.0/base_requirements.txt
7.0/Dockerfile
7.0/base_requirements.txt
8.0/Dockerfile
8.0/base_requirements.txt
9.0/Dockerfile
9.0/base_requirements.txt
HISTORY.rst

With the depreciation of Python 2 some libraries have dropped compatibility.
This restores the build for legacy version (and hopefully make the CI greener)

[<=10.0] Fix legacy build for Py2 based versions

---

10.0/base_requirements.txt
10.0/extra_requirements.txt
11.0/base_requirements.txt
11.0/extra_requirements.txt
12.0-buster/base_requirements.txt
12.0/base_requirements.txt
13.0/base_requirements.txt
14.0/base_requirements.txt
7.0/base_requirements.txt
8.0/base_requirements.txt
9.0/base_requirements.txt
HISTORY.rst

This includes security patches.

bump dependencies

---

14.0/base_requirements.txt
HISTORY.rst

When printing an invoice with a qrcode.
The call to reportlab.graphics.barcode.createBarcodeDrawing
would raise the following error:
AttributeError("'Image' object has no attribute 'fromstring'")

Fix qrcode generation in 14 (reportlab update)

---

HISTORY.rst
bin/docker-entrypoint.sh

Setting PostgreSQL application name using the hostname allows to easily distinguish the pods connected to PostgreSQL on Grafana dashboards.

feat(postgresql): set application name

---

15.0/base_requirements.txt

According to https://github.blog/2021-09-01-improving-git-protocol-security-github/

fix(v15): Replace deprecated git url in requirements

---

16.0/base_requirements.txt
HISTORY.rst

Context: the xlrd version 2.0.1 fails in odoo version 16, resulting in the error seen in the photo bellow. Resetting it back to the way odoo used it or using **xlrd >= 1.0.0** works, I tested in both cases.

[16.0] Fix: xlrd version

---

bin/runtests

As spotted by @ivantodorovich in https://github.com/camptocamp/docker-odoo-project/pull/216 I believe tests need to be re-enabled.

fix: re-enable tests

---

12.0/base_requirements.txt
13.0/base_requirements.txt
14.0/base_requirements.txt
15.0/base_requirements.txt
HISTORY.rst

By mistake, Reportlab was only pinned with Python >= 3.8
Consequence seen when build tried to install ReportLab 4.0.0 and failed building pycairo binary wheels.

[12.0-15.0] Pin reportlab for all Python versions

---

bin/runmigration
bin/runtests

In order to extract the DB dump from the image we want this folder to be standalone especially in the CI

Give a dedicated cachedb dir for volume mount

---

bin/docker-entrypoint.sh

In the new image layout, the `before-migrate-entrypoint.d` and `start-entrypoint.d` directories are no longer in the root directories but in the home directory of `odoo`, and the current code in the entrypoint would not find them, and therefore would not call them.
Fix the path in the docker entrypoint script.

[FIX] before entrypoint hooks not called

---

11.0/base_requirements.txt
12.0/base_requirements.txt
13.0/base_requirements.txt
14.0-bullseye/base_requirements.txt
14.0/base_requirements.txt
15.0/base_requirements.txt
16.0/base_requirements.txt
17.0/base_requirements.txt

Changes between 0.10.6 and 0.12.0
0.12.0 (2024-01-09)
+++++++++++++++++++
**Improvements**
* allow connecting to a local database server without password (using ident)
0.11.0 (2023-09-12)
+++++++++++++++++++
**Bugfixes**
* Fix the build and release workflow
**Build**
* Deprecate python 2.7, 3.5 and 3.6
* Support python 3.9, 3.10 and 3.11
0.10.7 (2022-05-24)
+++++++++++++++++++
**Bugfixes**
* Fix parsing of command line arguments (and related environment variables):
``--db-port``, ``--web-port``, ``--web-resp-status`` and
``--web-resp-retry-after``
**Improvements**
* Switch to Psycopg2 binary wheel
**Build**
* Test for python 3.6, 3.7 and 3.8

Update marabunta version to 0.12.0

---

bin/runtests

This will help a lot when having to debug a failing CI as it will allow to copy the list of installed addons to be able to reproduce locally.

Display installed addons before running tests in logs

---

11.0/base_requirements.txt
12.0/base_requirements.txt
13.0/base_requirements.txt
14.0-bullseye/base_requirements.txt
14.0/base_requirements.txt
15.0/base_requirements.txt
16.0/base_requirements.txt
17.0/base_requirements.txt
HISTORY.rst

sync the requirements of the different versions of python packages with Odoo's own requirements, and update some with our own.
Done for 11.0 -> 17.0

Update Python dependencies

---

.github/workflows/build.yaml

Always scanning prevent contributors to contribute as in my understanding we can only pass this test having the secrets which is not the case on forks.
As this is a public repository it is important to keep it open to contributions.

ci: only scan image on push

---

11.0/Dockerfile
12.0/Dockerfile
13.0/Dockerfile
14.0/Dockerfile
15.0/Dockerfile
16.0/Dockerfile
17.0/Dockerfile
18.0/Dockerfile

When numpy is imported, it will load some dependencies, if they are available. One of these is openblas, which will start some threads, which we will not be using, but which are consuming precious memory resources. By setting the OPENBLAS_NUM_THREADS environment variable to 1, we disable the creation of these threads and therefore reduce the memory usage of the Odoo workers.
This fixes the memory consumption issue when ninja dashboard is installed.

[FIX] disable openblas threads

---

12.0/Dockerfile
13.0/Dockerfile
14.0/Dockerfile
15.0/Dockerfile
16.0/Dockerfile
17.0/Dockerfile
18.0/Dockerfile
HISTORY.rst

It's the officially supported way to point to the config file since Odoo 10.0. OPENERP_SERVER will be officially deprecated in Odoo 19.0.
See: https://github.com/odoo/odoo/blob/4185fe84/odoo/tools/config.py#L464

imp: Replace environment variable OPENERP_SERVER with ODOO_RC
